[variables]
NODE_ENV = "production"

[phases.build]
nixPkgs = ["nodejs_18", "npm"]
aptPkgs = ["python3", "python3-pip", "build-essential"]

[phases.install]
cmds = [
    "npm ci --only=production"
]

[phases.setup]
nixPkgs = ["nodejs_18"]

[start]
cmd = "npm start"

[staticAssets]
# If you have any static assets, specify them here
# For example: "public" = "/app/public"

[buildImage]
name = "node:18-alpine"

# Health check configuration
[healthcheck]
command = ["curl", "-f", "http://localhost:${PORT:-5000}/api/health"]
interval = "30s"
timeout = "10s"
retries = 3
start_period = "40s"

# Port configuration
[ports]
web = "${PORT:-5000}"

# Environment variables that should be set during deployment
[variables.required]
MONGODB_URI = "Your MongoDB connection string"
JWT_SECRET = "Your JWT secret key"
FRONTEND_URL = "Your frontend URL"

# Optional environment variables with defaults
[variables.optional]
NODE_ENV = "production"
PORT = "5000"
JWT_EXPIRE = "30d"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
